language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=ansible14
  - TOX_ENV=ansible15
  - TOX_ENV=ansible16
  - TOX_ENV=ansible17
  - TOX_ENV=ansible18
install:
  - pip install setuptools-git
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  irc:
    - "irc.freenode.org#bsdploy"
  on_success: change
  on_failure: change
